// ── Central mock/data store ───────────────────────────────────────────────────
// When Supabase is connected this module is replaced by real DB queries.
// All pages import from here so mocks only live in one place.

export const HOSPITALS = [
  {
    id: 'h1',
    name: 'Lagos Family Health Centre',
    address: '12 Allen Avenue, Ikeja, Lagos',
    lga: 'Ikeja',
    state: 'Lagos',
    type: 'Private',
    phone: '+234 813 001 0001',
    email: 'info@lagosfamily.ng',
    about: 'A leading primary-care facility serving Ikeja and environs since 2009. We specialise in family medicine, maternal health, and preventive care.',
    specialties: ['Family Medicine', "Women's Health", 'Paediatrics'],
    rating: 4.9,
    reviews: 312,
    doctors: 4,
    verified: true,
    openNow: true,
    hours: 'Mon – Fri  8:00 AM – 6:00 PM\nSat  9:00 AM – 2:00 PM',
    gradient: 'from-teal-500 to-teal-700',
    initials: 'LF',
  },
  {
    id: 'h2',
    name: 'Victoria Island Wellness Clinic',
    address: '5 Adeola Odeku Street, Victoria Island, Lagos',
    lga: 'Eti-Osa',
    state: 'Lagos',
    type: 'Private',
    phone: '+234 813 002 0002',
    email: 'hello@viwellness.ng',
    about: 'A boutique wellness clinic focused on women\'s health, reproductive medicine, and general wellness. Equipped with modern diagnostic equipment.',
    specialties: ["Women's Health", 'Dermatology', 'General Practice'],
    rating: 4.8,
    reviews: 204,
    doctors: 3,
    verified: true,
    openNow: true,
    hours: 'Mon – Thu  8:00 AM – 4:00 PM\nFri  8:00 AM – 2:00 PM',
    gradient: 'from-violet-500 to-violet-700',
    initials: 'VI',
  },
  {
    id: 'h3',
    name: 'Abuja Care Clinic',
    address: '22 Gimbiya Street, Garki Area 11, Abuja',
    lga: 'AMAC',
    state: 'FCT',
    type: 'Private',
    phone: '+234 813 003 0003',
    email: 'care@abujacare.ng',
    about: 'A modern multi-specialty clinic serving Abuja\'s Garki and Wuse districts. We provide comprehensive outpatient care with same-day appointments.',
    specialties: ['General Practice', 'Cardiology', 'Orthopaedics'],
    rating: 4.7,
    reviews: 158,
    doctors: 5,
    verified: true,
    openNow: false,
    hours: 'Mon – Sat  10:00 AM – 7:00 PM',
    gradient: 'from-blue-500 to-blue-700',
    initials: 'AC',
  },
  {
    id: 'h4',
    name: 'Heart & Vascular Centre Lekki',
    address: '8 Admiralty Way, Lekki Phase 1, Lagos',
    lga: 'Eti-Osa',
    state: 'Lagos',
    type: 'Specialist',
    phone: '+234 813 004 0004',
    email: 'info@heartcentreng.com',
    about: 'Nigeria\'s premier specialist centre for cardiac care. We offer cardiology consultations, ECG, echocardiography and non-invasive vascular studies.',
    specialties: ['Cardiology', 'Internal Medicine'],
    rating: 4.9,
    reviews: 421,
    doctors: 6,
    verified: true,
    openNow: true,
    hours: 'Mon – Fri  9:00 AM – 5:00 PM',
    gradient: 'from-rose-500 to-rose-700',
    initials: 'HV',
  },
  {
    id: 'h5',
    name: "Children's Wellness Hub",
    address: '7 Katsina-Ala Crescent, Garki, Abuja',
    lga: 'AMAC',
    state: 'FCT',
    type: 'Specialist',
    phone: '+234 813 005 0005',
    email: 'hello@childwellness.ng',
    about: 'A paediatric specialist facility dedicated to child health from birth through adolescence. Home to experienced paediatricians and child psychologists.',
    specialties: ['Paediatrics', 'Child Psychology', 'Dentistry'],
    rating: 4.6,
    reviews: 97,
    doctors: 3,
    verified: false,
    openNow: true,
    hours: 'Mon – Sat  8:00 AM – 5:00 PM',
    gradient: 'from-amber-400 to-amber-600',
    initials: 'CW',
  },
];

export const DOCTORS_BY_HOSPITAL = {
  h1: [
    { id: '1', name: 'Dr. Adaeze Okafor', specialty: 'Family Medicine',   slotDuration: 15, fee: '₦8,000',  rating: 4.9, reviews: 128, avatarColor: 'teal',   availability: 'Today', bio: 'MBBS (Lagos), FMCGP. 12 years in family and preventive medicine.' },
    { id: '6', name: 'Dr. Blessing Eze',  specialty: "Women's Health",    slotDuration: 30, fee: '₦10,000', rating: 4.7, reviews: 64,  avatarColor: 'violet', availability: 'Tomorrow', bio: 'MBBS, MSc Obs & Gynae. Specialises in reproductive and maternal health.' },
    { id: '7', name: 'Dr. Kola Balogun',  specialty: 'Paediatrics',       slotDuration: 20, fee: '₦9,000',  rating: 4.8, reviews: 91,  avatarColor: 'amber',  availability: 'Today', bio: 'MBBS, FMCPaed. Experienced in childhood illnesses and immunisation.' },
  ],
  h2: [
    { id: '2', name: 'Dr. Tolu Adebayo',  specialty: "Women's Health",    slotDuration: 30, fee: '₦12,000', rating: 4.8, reviews: 96,  avatarColor: 'violet', availability: 'Tomorrow', bio: 'MBBS, MSc Obs & Gynae. Specialist in maternal health and reproductive medicine.' },
    { id: '8', name: 'Dr. Ngozi Obi',     specialty: 'Dermatology',       slotDuration: 20, fee: '₦15,000', rating: 4.9, reviews: 73,  avatarColor: 'rose',   availability: 'Today', bio: 'MBChB, FWACP Dermatology. Expert in skin conditions, acne, and cosmetic dermatology.' },
  ],
  h3: [
    { id: '3', name: 'Dr. Chinedu Eze',   specialty: 'General Practice',  slotDuration: 15, fee: '₦7,500',  rating: 4.7, reviews: 74,  avatarColor: 'blue',   availability: 'Today', bio: 'MBBS (Abuja). Expert in acute illnesses and chronic disease management.' },
    { id: '9', name: 'Dr. Yusuf Maikudi', specialty: 'Cardiology',        slotDuration: 30, fee: '₦18,000', rating: 4.8, reviews: 52,  avatarColor: 'rose',   availability: 'Wed', bio: 'MBBS, FMCCardiol. Cardiologist with 10 years in interventional cardiology.' },
  ],
  h4: [
    { id: '4', name: 'Dr. Emeka Nwosu',   specialty: 'Cardiology',        slotDuration: 30, fee: '₦20,000', rating: 4.9, reviews: 211, avatarColor: 'rose',   availability: 'Wed', bio: 'MBBS, FMCCardiol. Fellowship trained in interventional cardiology.' },
    { id:'10', name: 'Dr. Amaka Obiora',  specialty: 'Internal Medicine', slotDuration: 30, fee: '₦16,000', rating: 4.8, reviews: 88,  avatarColor: 'teal',   availability: 'Today', bio: 'MBBS, FMCP. Specialist in complex medical conditions and diagnostics.' },
  ],
  h5: [
    { id: '5', name: 'Dr. Fatima Musa',   specialty: 'Paediatrics',       slotDuration: 20, fee: '₦9,500',  rating: 4.6, reviews: 55,  avatarColor: 'amber',  availability: 'Today', bio: 'MBBS, FMCPaed. Passionate advocate for child health.' },
    { id:'11', name: 'Dr. Ibrahim Sule',  specialty: 'Dentistry',         slotDuration: 30, fee: '₦8,500',  rating: 4.5, reviews: 34,  avatarColor: 'blue',   availability: 'Tomorrow', bio: 'BDS (Ibadan). Specialist in preventive and restorative dentistry.' },
  ],
};

